id: AE71D2667
title: Aspiration for the Long Life of Dezhung Rinpoche (Jampa Kunga Tenpé Nyima)
type: translation
pechas:
- IF6E5023A
- I6569AA2C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:56:23.713003
  last_modified_at: 2023-01-04 11:56:23.713011
  collections:
  - Gatön Ngawang Lekpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IF6E5023A/7249: 4F64
  I6569AA2C/310C: 4F64
